# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: macos-11

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install bash
          brew install tunnelblick
          brew tap benwebber/tunnelblickctl
          brew install tunnelblickctl
          gem install bashly

      # Run bashly
      - run: bashly generate

      # Smoke test
      - name: Smoke test
        run: ./aws-vpn list


