# This is a basic workflow to help you get started with Actions

name: release

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: macos-11

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - run: brew install tunnelblick
      - run: brew tap benwebber/tunnelblickctl
      - run: brew install tunnelblickctl

      # Install bashly
      - run: gem install bashly

      # Run bashly
      - run: bashly generate

      # Smoke test
      - name: Smoke test
        run: ./aws-vpn list


