name: release

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: macos-11
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install bash
          gem install bashly

      # Run bashly
      - run: |
          bashly generate
          mkdir bin
          cp aws-vpn bin/aws-vpn

      - uses: thedoctor0/zip-release@master
        with:
          type: tar
          directory: bin
          filename: aws-vpn.tar.gz

      - uses: ncipollo/release-action@v1
        with:
          artifacts: bin/aws-vpn.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"

      - uses: mislav/bump-homebrew-formula-action@v1
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: aws-vpn
          formula-path: Formula/aws-vpn.rb
          homebrew-tap: mazerte/homebrew-software
          download-url: https://github.com/mazerte/aws-vpn/releases/download/${{ steps.extract-version.outputs.tag-name }}/aws-vpn.tar.gz
          commit-message: |
            {{formulaName}} {{version}}
