name: release

on:
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: macos-11
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install bash
          gem install bashly

      # Run bashly
      - run: |
          bashly generate
          mkdir bin
          cp aws-vpn bin/aws-vpn

      - uses: thedoctor0/zip-release@master
        with:
          type: tar
          path: bin/
          filename: release.tar.gz

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
